user:
  service:
    list:
      uri: "http://192.168.1.37:8081"
    username: Superuser
    password: admin

spring:
  datasource:
    url: jdbc:postgresql://172.17.0.4:5432/users
    username: postgres
    password: admin
  jpa:
    show-sql: true
  flyway:
    schemas:
      - user_management

